name: Train Model and Log into MLflow

on:
  workflow_dispatch:
    inputs:
      n_estimators:
        description: "Number of trees"
        required: true
        default: "100"

      max_depth:
        description: "Maximum tree depth"
        required: true
        default: "5"

  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train the Model and Log into MLflow
        run: |
          python src/train.py \
            --n_estimators ${{ github.event.inputs.n_estimators || '100' }} \
            --max_depth ${{ github.event.inputs.max_depth || '5' }}