name: Train Model and Log into MLflow

on:
  workflow_dispatch:
    inputs:
      n_estimators:
        description: "Number of trees"
        required: true
        default: "100"

      max_depth:
        description: "Maximum tree depth"
        required: true
        default: "5"

  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Test S3 Access
        run: |
          aws s3 ls s3://rajini-demo

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train the Model and Log into MLflow
        run: |
          python src/train.py \
            --n_estimators ${{ github.event.inputs.n_estimators || '100' }} \
            --max_depth ${{ github.event.inputs.max_depth || '5' }}